repos:
  # 기본 위생 체크
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml

  # Ruff: 포맷 + 린트
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      # 1) 자동 포맷 (줄맞춤/스타일) — Black 대체
      - id: ruff-format
        stages: [pre-commit]

      # 2) import 정렬만 자동 수정
      - id: ruff
        name: ruff (fix imports only)
        args:
          [
            "--select",
            "I",
            "--fix",
            "--exit-non-zero-on-fix",
            "--output-format",
            "concise",
          ]
        stages: [pre-commit]

      # 3) 나머지 린트는 위치만 표시(수정 X)
      - id: ruff
        name: ruff (lint report only)
        args:
          [
            "--select",
            "E,F,B,UP,ANN,W,C90,ISC,COM",
            "--ignore",
            "ANN101,ANN102",
            "--output-format",
            "concise",
          ]
        stages: [pre-commit]

  # 타입 체크: 에러 위치 출력
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        files: ^app/|^scripts/
        stages: [pre-commit]

  # (선택) 커밋 메시지 규칙 검사
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
