minimum_pre_commit_version: "3.7.0"
fail_fast: true

exclude: |
  (?x)^(
    .*/migrations/.*|
    .*/node_modules/.*|
    .*/dist/.*|
    .*/build/.*|
    .*/.venv/.*|
    .*/venv/.*|
    .*/.mypy_cache/.*|
    .*/.ruff_cache/.*|
    .*/coverage/.*|
    .*/_generated/.*|
    .*/__pycache__/.*|
    .*\.(min\.js|min\.css)
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      # 1) 포맷
      - id: ruff-format
        name: ruff-format (code formatter)
        stages: [pre-commit]

      # 2) 안전 자동수정 (임포트 + 자잘한 포맷성 규칙)
      - id: ruff
        name: ruff (safe autofix)
        args:
          [
            "--select",
            "I,E,W,UP,COM,ISC,F401",
            "--ignore",
            "ANN101,ANN102,ANN201",
            "--fix",
            "--exit-non-zero-on-fix",
            "--output-format",
            "concise",
          ]
        stages: [pre-commit]

      # 3) 리포트만
      - id: ruff
        name: ruff (lint report only)
        args:
          [
            "--select",
            "E,F,B,UP,ANN,W,C90,ISC,COM",
            "--ignore",
            "ANN101,ANN102,ANN201",
            "--output-format",
            "concise",
          ]
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        name: mypy (type check)
        additional_dependencies: [types-requests, types-PyYAML]
        files: ^(app/|scripts/)
        args:
          [
            "--disable-error-code",
            "no-untyped-def",
            "--pretty",
            "--show-error-codes",
            "--no-error-summary",
          ]
        stages: [pre-commit]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
