# .pre-commit-config.yaml
minimum_pre_commit_version: "3.7.0"
fail_fast: true

# 공통 제외 경로 (ruff/.pre-commit 모두 일치)
exclude: |
  (?x)^(
    .*/migrations/.*|
    .*/node_modules/.*|
    .*/dist/.*|
    .*/build/.*|
    .*/.venv/.*|
    .*/venv/.*|
    .*/.mypy_cache/.*|
    .*/.ruff_cache/.*|
    .*/coverage/.*|
    .*/_generated/.*|
    .*/__pycache__/.*|
    .*\.(min\.js|min\.css)
  )$

repos:
  # 기본 포맷/체크 훅
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml

  # Ruff (포매터 + 린터)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
      - id: ruff-format

  # Mypy (타입 체크)
  - repo: local
    hooks:
      - id: mypy
        name: mypy (uv)
        entry: uv run mypy --config=pyproject.toml
        language: system
        types: [python]
        pass_filenames: false # 파일 목록 대신 설정 기준으로 전체 검사(선호)

  # 커밋 메시지 규칙(Conventional Commits)
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
