# 목적: release/* 브랜치에 변경이 올 때 빠른 스모크 테스트로 기본 동작 이상 유무 확인
# 트리거: release/* 브랜치 push, 수동 실행
# 보호규칙: release/* 의 필수 체크로 ci/smoke 등록

name: Release Smoke

on:
  push:
    branches:
      - "release/**" # 릴리스 후보 브랜치에 커밋 푸시 시
  workflow_dispatch: # 수동 실행

permissions:
  contents: read

jobs:
  smoke:
    name: ci/smoke # ✅ 스모크 테스트(핵심 경로만 빠르게)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python # Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install minimal deps # 최소 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run smoke tests # 스모크 마커가 있으면 해당만 실행
        run: |
          pytest -q -m "smoke" || pytest -q
